blank_issues_enabled: false
contact_links:
  - name: View documentation ðŸ“š
    url: https://commercelayer.io/developers
    about: Explore our API reference and open-source tools.
  - name: Slack community ðŸ’¬
    url: https://commercelayer.io/developers
    about: Community discussions, interactive support, contributor help.
